mode: backtest
start_date: 2025-06-12
end_date: 2025-06-13
primary_interval: 1h
initial_cash: 100000
margin_requirement: 0.0
show_reasoning: false
show_agent_graph: true
signals:
  intervals: ["1h", "4h"]
  tickers: ["BTCUSDT", "ETHUSDT"]
  strategies: ['EMAStrategy']
# , "RSIStrategy"]
model:
  name: "meta-llama/llama-4-scout-17b-16e-instruct" # 使用Llama模型
  provider: "groq"       # 使用groq提供商
  base_url: "https://api.groq.com"  # 正确

  #grop uri 格式 
  #base_url: "https://api.groq.com"
